services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    ports:
      - "4444:4444"

  missionqa:
    build: .
    depends_on:
      - selenium
    environment:
      TAGS: ${TAGS:-}
      BROWSER: chromeheadless
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
    volumes:
      - ./artifacts:/app/artifacts
